name: eidas
networks:
  eidas:
    name: eidas
  idporten:
    name: idporten

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6400:6379"
    networks:
      - eidas
    command: redis-server --maxmemory-policy allkeys-lru
  eidas-idporten-connector:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    environment:
      spring_profiles_active: local-docker
      OTEL_SDK_DISABLED: "true"
    ports:
      - "8088:8086"
      - "5099:5006"
    networks:
      - eidas
      - idporten
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/webapps
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -jar application.jar

