---
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  http2:
    enabled: true
  error:
    whitelabel:
      enabled: true
# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: redis
spring:
  application:
    name: eidas-idporten-connector
    environment: prod
  main:
    lazy-initialization: false
    banner-mode: "off"
    log-startup-info: false
  cache:
    type: redis
  data:
    redis:
      connect-timeout: 3s
      timeout: 3s
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 2592000
          stale-while-revalidate: 604800
          cache-public: true
          must-revalidate: true
          stale-if-error: 604800
          no-transform: true
  session:
    store-type: redis
eidas:
  countries:
    included:
      - AT
      - BE
      - BE
      - BG
      - CY
      - CZ
      - CZ
      - DK
      - EE
      - EL
      - ES
      - EU
      - FI
      - FR
      - HR
      - IS
      - IT
      - IT
      - LI
      - LT
      - LU
      - LV
      - MT
      - NL
      - PL
      - PT
      - RO
      - SE
      - SK
      - SL
    test: false
  eu-connector:
    issuer-name: ${eidas.cache.request-issuer-name}
  cache:
    response-issuer-name: specificCommunicationDefinitionConnectorserviceResponse
    request-issuer-name: specificCommunicationDefinitionConnectorserviceRequest
    algorithm: SHA-256
    light-response-lifetime-seconds: 120
    oidc-request-state-lifetime-seconds: 700
  acr:
    supported-acr-values:
      - http://eidas.europa.eu/LoA/low
      - http://eidas.europa.eu/LoA/substantial
      - http://eidas.europa.eu/LoA/high
    acr-value-map:
      eidas-loa-low: "http://eidas.europa.eu/LoA/low"
      eidas-loa-substantial: "http://eidas.europa.eu/LoA/substantial"
      eidas-loa-high: "http://eidas.europa.eu/LoA/high"
  oidc-server:
    par-lifetime-seconds: 60
    authorization-lifetime-seconds: 60
    accesstoken-lifetime-seconds: 120
    authorization-response-iss-parameter-supported: true
    response-modes-supported:
      - query
      - query.jwt
    scopes-supported:
      - openid
      - profile
      - eidas:mds
    acr-values:
      - eidas-loa-low
      - eidas-loa-substantial
      - eidas-loa-high
  lightprotocol-cache:
    response-issuer-name: specificCommunicationDefinitionProxyserviceResponse
    request-issuer-name: specificCommunicationDefinitionProxyserviceRequest
    issuer-name: specificCommunicationDefinitionProxyserviceResponse
    algorithm: SHA-256
    light-response-lifetime-seconds: 120
    oidc-request-state-lifetime-seconds: 700
  freg-gw:
    enabled: true
    read-timeout-ms: 5000
    connect-timeout-ms: 5000
    base-uri: http://eidas-freg-gateway-service:8080
    api-key: ${FREG_GW_API_KEY}
digdir:
  audit:
    application-name: ${spring.application.name}
    application-environment: ${spring.application.environment}
    log-dir:
    filters:
      bearer-token: false

---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import:
      - 'optional:file:/etc/config/'
